### ISSUE TITLE
0.29.0 release hashes don't match for windows build

### ISSUE THREAD

**Issue by yzaguirre** [lunaryorn/mdcat#215] opened 2022-11-28 18:25 UTC

**Comment by lunaryorn** [comment] 2022-11-28 18:57
Thanks for reporting. I can't reproduce this, tho.  I downloaded all files from the 0.29 release and ran the checksums. All passed:

```console
$ ls
B2SUMS.txt                               mdcat-0.29.0-x86_64-pc-windows-msvc.zip        SHA512SUM.txt
mdcat-0.29.0-x86_64-apple-darwin.tar.gz  mdcat-0.29.0-x86_64-unknown-linux-musl.tar.gz
$ sha512sum --ignore-missing -c SHA512SUM.txt
mdcat-0.29.0-x86_64-apple-darwin.tar.gz: OK
mdcat-0.29.0-x86_64-pc-windows-msvc.zip: OK
mdcat-0.29.0-x86_64-unknown-linux-musl.tar.gz: OK
$ b2sum --ignore-missing -c B2SUMS.txt
mdcat-0.29.0-x86_64-apple-darwin.tar.gz: OK
mdcat-0.29.0-x86_64-pc-windows-msvc.zip: OK
mdcat-0.29.0-x86_64-unknown-linux-musl.tar.gz: OK
```

I'm closing this issue, because without more details I can't do anything here 🙂

**Closed** 2022-11-28 18:57 UTC
