### ISSUE TITLE
`mdcat` can't handle badges (Travis CI) in iTerm2

### ISSUE THREAD

**Issue by geoff-nixon** [lunaryorn/mdcat#83] opened 2019-07-29 15:52 UTC
The current version of `mdcat` hangs when trying to render badge syntax in the current version of iTerm2, as in the project's own README.md:

```
[![Current release](https://img.shields.io/crates/v/mdcat.svg)][crates]
[![License](https://img.shields.io/github/license/lunaryorn/mdcat.svg)][license]
[![Build status](https://travis-ci.com/lunaryorn/mdcat.svg?branch=master)][travis]
[![Dependabot Status](https://api.dependabot.com/badges/status?host=github&repo=lunaryorn/mdcat)](https://dependabot.com)
```

It just hangs:

<img width="682" alt="mdcat-README md" src="https://user-images.githubusercontent.com/3162811/62062575-1bdf8400-b1de-11e9-9acf-49fbad1fd537.png">

Taking that block out resolves the issue.

Renders as 
```
[Current release[1]]crates[2]
[License[3]]license[4]
[Build status[5]]travis[6]
[Dependabot Status[7]](https://dependabot.com)
```
in Terminal.app.

...?

**Comment by lunaryorn** [comment] 2019-07-29 16:18
Hangs forever?  Maybe you’ve got network issues and it can’t fetch images?

If that’s not the cause I guess you’ll have to debug it.  See I don’t have this issue so I can’t reproduce it now and I really don’t have time to try.

**Comment by lunaryorn** [comment] 2019-08-07 21:19
@geoff-nixon I'm closing this issue; please feel free to reopen if you've got more debug info.

**Closed by lunaryorn** 2019-08-07 21:19 UTC
Labels: bug
